name: Testing Github Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run a multi-line script
        run: |
          s="${{ secrets.TOKEN }} | base64"
          echo "::set-output name=secret::$s" 
          echo "::set-output name=secret::${{ secrets.TOKEN}}" 
