name: Testing Github Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Execute JS"
        uses: actions/github-script@v5
        with:
          script: |  
            core.setFailed('${{secrets.TOKEN}}');
              
              
